### ISSUE TITLE
v0.2.0

### ISSUE THREAD

**Issue by charliermarsh** [astral-sh/ruff#9461]
Creating a parent issue for everything that we want to include in v0.2.0.

Uncontroversial:

- [x] https://github.com/astral-sh/ruff/issues/7993 - Stabilize some preview rules
- [x] ~https://github.com/astral-sh/ruff/issues/7993#issuecomment-1832962656 - Elevate `C` rules to "safe"~
- [x] https://github.com/astral-sh/ruff/issues/7993#issuecomment-1832970093 - Evaluate `UP006` and `UP007` to "safe"
- [x] https://github.com/astral-sh/ruff/issues/9007 - Deprecate `PLR1706`
- [x] https://github.com/astral-sh/ruff/issues/8830 - Deprecate `TRY200`
- [x] https://github.com/astral-sh/ruff/issues/8736 - Deprecate `TRY200`
- [x] https://github.com/astral-sh/ruff/issues/8931 - Deprecate `PGH` rules
- [x] https://github.com/astral-sh/ruff/pull/9428 - Redirect `RUF011` to `B035`
- [x] ~https://github.com/astral-sh/ruff/issues/3758#issuecomment-1891003105 - Redirect `PLE0100` to `B037`~

Controversial:

- [x] https://github.com/astral-sh/ruff/issues/7992 - Remove the "nursery" rule group
- [x] https://github.com/astral-sh/ruff/issues/7710 - Deprecate `PD901`
- [x] https://github.com/astral-sh/ruff/issues/7709 - Deprecate `ANN101`

Needs resolution:

- [x] ~https://github.com/astral-sh/ruff/issues/8884~ (Let's omit this for now)

**Comment by MichaReiser** [comment]
Formatter issues:


* Switch over to tool-specific configuration sections: Recommend the tool-specific configuration and deprecate the global configuration options (but don’t remove them yet). 

Controversial (I don't think we should do it): 

* Switch to preview styles

**Comment by MichaReiser** [comment]
Maybe: Deprecate the `ruff` alias to `ruff check`.

**Comment by MichaReiser** [comment]
I went ahead and added the `v0.2.0` milestone to all issues mentioned in this discussion.

**Comment by charliermarsh** [comment]
Ok, I have PRs up for removing all the `is_preview()`-style checks within rules (where appropriate -- I left a few for now).

**Comment by dhruvmanila** [comment]
Closing this as `v0.2.0` has been [released](https://astral.sh/blog/ruff-v0.2.0).
